import { useCallback, useEffect, useState } from "react";
import { AlertOctagon, ArrowRight, Camera, Check, ChevronLeft, CircleDot, CloudOff, HardHat, HelpCircle, LogOut, MapPin, Navigation, Radio, RefreshCw, ShieldCheck, Signal, Siren, WifiOff } from "lucide-react";

const API = "/api/v1";
const UNITS = { ALPHA: { device: "OnePlus Nord CE5", start: [12, 82] }, BRAVO: { device: "Moto G86 Power 5G", start: [88, 18] } };
const FLOW = ["DISPATCHED", "ACCEPTED", "EN_ROUTE", "ON_SITE", "INSPECTION_STARTED", "COMPLETED"];
const ACTIONS = { DISPATCHED: ["ACCEPTED", "REJECTED"], ACCEPTED: ["EN_ROUTE"], EN_ROUTE: ["ON_SITE"], ON_SITE: ["INSPECTION_STARTED"], INSPECTION_STARTED: ["COMPLETED"] };
const ACTION_LABEL = { ACCEPTED: "Accept assignment", EN_ROUTE: "Start route", ON_SITE: "Confirm on site", INSPECTION_STARTED: "Begin inspection", COMPLETED: "Submit inspection", REJECTED: "Reject" };
const CHECKS = { area_isolated: "Area isolated and access controlled", visible_cracks_checked: "Visible cracks and joints checked", supports_checked: "Nearby supports visually checked", sensor_mount_checked: "Sensor mounting inspected" };

function load(key, fallback = null) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }
function save(key, value) { localStorage.setItem(key, JSON.stringify(value)); }

async function request(path, options = {}) {
  const response = await fetch(`${API}${path}`, { headers: { "Content-Type": "application/json", ...(options.token ? { Authorization: `Bearer ${options.token}` } : {}) }, ...options, body: options.body && JSON.stringify(options.body) });
  if (!response.ok) throw new Error((await response.json().catch(() => ({}))).detail || "Request failed");
  return response.json();
}

function IdentityScreen({ onReady }) {
  const [unit, setUnit] = useState(null); const [pin, setPin] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const connect = async () => { if (!unit || pin.length < 4) return; setBusy(true); setError(""); try { const session = await request("/auth/login", { method: "POST", body: { role: "INSPECTION", unit_id: unit, pin } }); save("inspection_identity", { unit, token: session.access_token }); onReady({ unit, token: session.access_token }); } catch (reason) { setError(reason.message); } finally { setBusy(false); } };
  return <main className="phone-shell identity-screen"><div className="identity-glow"></div><section className="identity-card"><div className="mobile-logo"><HardHat size={27}/></div><span className="mobile-kicker">BHARATNEX • FIELD OPERATIONS</span><h1>Geo-Sentry</h1><p>Select this phone’s inspection identity. The selection stays on this device.</p><div className="unit-select">{Object.entries(UNITS).map(([id, info])=><button className={unit===id?"chosen":""} key={id} onClick={()=>setUnit(id)}><span>UNIT</span><strong>{id}</strong><small>{info.device}</small><CircleDot size={18}/></button>)}</div><label className="pin-label">PROTOTYPE ACCESS PIN<input inputMode="numeric" type="password" value={pin} onChange={e=>setPin(e.target.value)} placeholder="Enter PIN" maxLength={32}/></label>{error&&<p className="form-error">{error}</p>}<button className="primary mobile-wide" disabled={!unit||pin.length<4||busy} onClick={connect}>{busy?"Connecting…":"Activate inspection unit"}<ArrowRight size={18}/></button><small className="scope-note"><ShieldCheck size={13}/> Closed-network prototype • not a certified safety system</small></section></main>;
}

function RouteMap({ unit, node, status }) {
  const target = node === "NODE_B" ? [67,62] : [22,42]; const start = UNITS[unit].start; const progress = { DISPATCHED:.05, ACCEPTED:.12, EN_ROUTE:.52, ON_SITE:.92, INSPECTION_STARTED:1, COMPLETED:1 }[status] || 0; const x=start[0]+(target[0]-start[0])*progress; const y=start[1]+(target[1]-start[1])*progress;
  return <div className="route-map"><div className="tunnel t1"></div><div className="tunnel t2"></div><svg viewBox="0 0 100 100" preserveAspectRatio="none"><line x1={start[0]} y1={100-start[1]} x2={target[0]} y2={100-target[1]} stroke="#28445b" strokeWidth="2" strokeDasharray="4 4"/><line x1={start[0]} y1={100-start[1]} x2={x} y2={100-y} stroke="#34d399" strokeWidth="2.5"/></svg><div className="target" style={{left:`${target[0]}%`,top:`${100-target[1]}%`}}><AlertOctagon size={16}/><span>{node?.replace("_"," ")}</span></div><div className="unit-pin" style={{left:`${x}%`,top:`${100-y}%`}}><Navigation size={15}/></div><span className="local-label">LOCAL XY ROUTE • SIMULATED</span></div>;
}

function InspectionApp() {
  const [identity, setIdentity] = useState(()=>load("inspection_identity")); const [assignment, setAssignment] = useState(()=>load("cached_assignment")); const [online, setOnline] = useState(navigator.onLine); const [live, setLive] = useState(false); const [syncing, setSyncing] = useState(false); const [error, setError] = useState(""); const [rejecting, setRejecting] = useState(false); const [reason, setReason] = useState(""); const [notes, setNotes] = useState(""); const [severity, setSeverity] = useState("MODERATE"); const [checklist, setChecklist] = useState({}); const [photos, setPhotos] = useState([]);
  const refresh = useCallback(async()=>{ if(!identity) return; try { const data=await request(`/units/${identity.unit}/assignment`); setAssignment(data.assignment); save("cached_assignment",data.assignment); setOnline(true); } catch { setOnline(false); } },[identity]);
  const flushQueue = useCallback(async()=>{ if(!identity||!navigator.onLine) return; const queue=load("inspection_queue",[]); if(!queue.length) return; setSyncing(true); const remaining=[]; for(const item of queue){ try{await request(item.path,{method:"POST",token:identity.token,body:item.body});}catch{remaining.push(item);} } save("inspection_queue",remaining); setSyncing(false); refresh(); },[identity,refresh]);
  useEffect(()=>{ const up=()=>{setOnline(true);flushQueue();}; const down=()=>setOnline(false); window.addEventListener("online",up);window.addEventListener("offline",down);return()=>{window.removeEventListener("online",up);window.removeEventListener("offline",down);};},[flushQueue]);
  useEffect(()=>{if(!identity)return;refresh();const timer=setInterval(refresh,4000);const protocol=location.protocol==="https:"?"wss":"ws";const ws=new WebSocket(`${protocol}://${location.host}${API}/live`);ws.onopen=()=>{setLive(true);ws.send("ready");};ws.onmessage=()=>refresh();ws.onclose=()=>setLive(false);return()=>{clearInterval(timer);ws.close();};},[identity,refresh]);
  useEffect(()=>{if(online)flushQueue();},[online,flushQueue]);
  const latest=assignment?.latest_reading; const decision=latest?.decision; const currentStatus=assignment?.status||"AVAILABLE"; const step=Math.max(0,FLOW.indexOf(currentStatus)); const nextActions=ACTIONS[currentStatus]||[];
  const submit=async(status,extra={})=>{ if(!assignment)return; const payload={status,notes,severity,checklist,photos,...extra}; const item={path:`/incidents/${assignment.id}/inspection`,body:payload}; if(!navigator.onLine){const queue=load("inspection_queue",[]);queue.push(item);save("inspection_queue",queue);setAssignment({...assignment,status});save("cached_assignment",{...assignment,status});setOnline(false);return;} try{await request(item.path,{method:"POST",token:identity.token,body:payload});setRejecting(false);await refresh();}catch(reason){if(reason.message.includes("expired")){logout();}else setError(reason.message);}};
  const logout=()=>{localStorage.removeItem("inspection_identity");setIdentity(null);setAssignment(null);};
  const photo=event=>{const file=event.target.files?.[0];if(!file||photos.length>=3)return;const reader=new FileReader();reader.onload=()=>setPhotos(old=>[...old,String(reader.result)]);reader.readAsDataURL(file);};
  if(!identity)return <IdentityScreen onReady={setIdentity}/>;
  return <main className="phone-shell"><header className="mobile-header"><div className="mobile-brand"><div className="mobile-logo small"><HardHat size={20}/></div><div><strong>GEO-SENTRY</strong><span>INSPECTION UNIT {identity.unit}</span></div></div><div className="connection"><span className={online?"connected":"disconnected"}>{online?<Signal size={14}/>:<WifiOff size={14}/>} {online?(live?"LIVE":"POLLING"):"OFFLINE"}</span><button onClick={logout} aria-label="Change unit"><LogOut size={17}/></button></div></header>
    {!assignment?<section className="standby"><div className="radar"><Radio size={36}/><i></i></div><span>UNIT {identity.unit} • AVAILABLE</span><h1>Awaiting assignment</h1><p>The command centre will dispatch this unit when an inspection is required.</p><button onClick={refresh}><RefreshCw size={16}/> Check now</button>{syncing&&<small>Synchronizing queued updates…</small>}</section>:
    <><section className={`assignment-hero ${assignment.state?.toLowerCase()}`}><div className="incident-row"><span>INC-{String(assignment.id).padStart(3,"0")}</span><strong>{assignment.state}</strong></div><h1>Inspection assigned</h1><p>{assignment.zone} • {assignment.node_id?.replace("_"," ")}</p><div className="metrics"><div><span>RISK</span><strong>{Math.round(decision?.risk||0)}</strong></div><div><span>CONFIDENCE</span><strong>{Math.round(decision?.confidence||0)}%</strong></div><div><span>TREND</span><strong>{decision?.trend?.replaceAll("_"," ")||"—"}</strong></div></div></section>
    <section className="phone-content"><RouteMap unit={identity.unit} node={assignment.node_id} status={currentStatus}/><div className="progress"><div className="progress-head"><span>MISSION PROGRESS</span><strong>{currentStatus.replaceAll("_"," ")}</strong></div><div className="progress-line">{FLOW.map((item,index)=><i className={index<=step?"done":""} key={item}></i>)}</div></div>
    <section className="safety-card"><Siren size={20}/><div><span>SAFETY RESPONSE</span><p>{assignment.recommendation}</p></div></section>
    <section className="evidence"><span>WHY FLAGGED</span><div>{decision?.reason_codes?.map(code=><em key={code}>{code.replaceAll("_"," ")}</em>)}</div></section>
    {currentStatus==="INSPECTION_STARTED"&&<section className="inspection-form"><h2>Inspection findings</h2>{Object.entries(CHECKS).map(([key,label])=><label className="check" key={key}><input type="checkbox" checked={!!checklist[key]} onChange={e=>setChecklist({...checklist,[key]:e.target.checked})}/><i>{checklist[key]&&<Check size={14}/>}</i><span>{label}</span></label>)}<label>OBSERVED SEVERITY<select value={severity} onChange={e=>setSeverity(e.target.value)}><option>LOW</option><option>MODERATE</option><option>HIGH</option><option>URGENT</option></select></label><label>FINDINGS<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Describe visible conditions and actions taken…"/></label><div className="photo-row"><label className="photo-button"><Camera size={18}/> Add photo<input type="file" accept="image/*" capture="environment" onChange={photo}/></label><span>{photos.length}/3 attached</span></div></section>}
    {error&&<p className="form-error">{error}</p>}<div className="action-stack">{nextActions.filter(a=>a!=="REJECTED").map(action=><button className="primary mobile-wide" key={action} onClick={()=>submit(action)}>{ACTION_LABEL[action]}<ArrowRight size={18}/></button>)}{nextActions.includes("REJECTED")&&<button className="secondary mobile-wide" onClick={()=>setRejecting(true)}>Reject assignment</button>}<button className="assist" onClick={()=>submit("ASSISTANCE_REQUESTED",{notes:"Inspection unit requested command-centre assistance."})}><HelpCircle size={18}/> Request assistance</button></div></section></>}
    {rejecting&&<div className="modal-back"><div className="reject-modal"><button className="back" onClick={()=>setRejecting(false)}><ChevronLeft size={17}/> Back</button><AlertOctagon size={30}/><h2>Reject assignment?</h2><p>A reason is required so the command centre can reassign the incident safely.</p><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason for rejection"/><button className="danger mobile-wide" disabled={reason.trim().length<3} onClick={()=>submit("REJECTED",{rejection_reason:reason})}>Reject and return to queue</button></div></div>}
    {!online&&<div className="offline-banner"><CloudOff size={16}/> Offline mode • updates will synchronize automatically</div>}</main>;
}

export default InspectionApp;
